version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    volumes:
      - ~/docker/mongo:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: changeme

  app_bot:
    env_file:
      - .env
    
    build: .
    #command: /bin/bash -c "sleep 15; python3 bot.py"
    container_name: app_bot
    volumes:
      - src:/usr/local/src
    depends_on:
      - mongo
    links:
      - mongo

volumes:
  src: {}