version: '3.1'

services:

  mongo:
    image: mongo
    ports:
      - 27017:27017
    restart: always
    volumes:
      - ~/docker/mongo:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: changeme

  # ===============
  # Mongo Express service
  # ===============
  # available at http://localhost:8081
  # NOTE: this is totally optional, feel free to comment out below if prod
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    depends_on:
      - mongo
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: changeme
      ME_CONFIG_MONGODB_URL: mongodb://root:changeme@mongo:27017/

  # ===============
  # Logging service
  # ===============
  # available at http://localhost:9999
  # NOTE: this is totally optional, feel free to comment out below if prod
  app_dozzle:
    container_name: dozzle
    image: amir20/dozzle:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 9999:8080

volumes:
  src: {}